language: node_js
sudo: false
services:
  - docker
node_js:
  - "8.9"
install:
  - npm install
script:
   - ng build --prod
before_script:
  - docker pull jenkins/jenkins
script:
  - docker run -it -p 8084:80 jenkins/jenkins
branches:
  only:
  - master
  - Login-FrontPrincipal
  - /.*/ 


