language: node_js
sudo: false
services:
  - docker
node_js:
  - "8.9"
install:
  - npm install
script:
   - ng build --prod
before_script:
  - docker pull gizra/drupal-lamp
script:
  - docker run -it -p 8080:80 gizra/drupal-lamp  
branches:
  only:
  - master
  - Login-FrontPrincipal
  - /.*/ 


