language: node_js
sudo: false
services:
  - docker
node_js:
  - "8.9"
install:
  - npm install
script:
   - ng build --prod
before_script:
  - docker ps
script:
  - docker ps
branches:
  only:
  - master
 


